"""
OpenAVC Philips Hue Bridge Driver (CLIP API v2).

Controls Philips Hue lights, rooms, zones, and scenes via the local CLIP v2
REST API on a Hue Bridge over HTTPS, with live state pushed by the bridge's
Server-Sent Events stream.

API generation:
  This driver targets the v2 / CLIP v2 API (HTTPS, /clip/v2/resource/...),
  the current Hue API generation. It requires a square Hue Bridge (BSB002)
  on firmware 1948086000 or newer — every bridge updated since late 2019
  qualifies. The round 2012 bridge (BSB001) never received the v2 API and
  is not supported by this driver version.

Why Python:
  A Hue Bridge is inherently a many-unit controller — one bridge drives up
  to 50+ lights and dozens of rooms/zones, all keyed by per-install ids.
  Python is required for the parts YAML cannot express:
    - every light and group is a child entity enumerated from the bridge,
      each light with a per-child schema matching its real capability set
      (an on/off plug shows no brightness field, a white-ambiance light no
      color control) and per-light color-temperature bounds taken from the
      light's own mirek_schema;
    - the SSE event stream carries JSON arrays of event envelopes that fan
      out into per-child state updates;
    - a "Pair with Bridge" setup wizard that runs while the device is
      OFFLINE (no app key means the driver can't connect, and commands
      need a connected device);
    - typed connection faults (a rejected or missing app key shows as
      "authentication failed" on the device card, not a generic offline).

Protocol reference:
  The official CLIP v2 reference is gated behind a developer-portal login.
  This driver is built against the home-assistant-libs/aiohue v2
  implementation (a mature open-source client that mirrors the official
  spec). Facts verified there: the base URL and hue-application-key header,
  the /eventstream/clip/v2 SSE endpoint (headers, envelope format,
  last-event-id replay, add/update/delete event types), the resource
  schemas (light/grouped_light/room/zone/scene/device/bridge_home/bridge/
  zigbee_connectivity), partial-body PUT shapes, the {"data": [...],
  "errors": [...]} response envelope, app-key creation via the v1 POST /api
  endpoint (error 101 = link button), the bridge's 3-concurrent-request /
  429 behavior, and the absence of any server-side SSE keepalive.

Push vs. poll:
  Push. The bridge streams every resource change over one Server-Sent
  Events connection (GET /eventstream/clip/v2); light, group, scene-list,
  and reachability changes land in child state the moment they happen —
  including changes made from the Hue app or dimmer switches. Polling
  stays on as the baseline resync (default 30 s, one bulk
  GET /clip/v2/resource per cycle): the bridge sends no keepalive on the
  stream, so a silently dead stream is detected by reopening it after 90 s
  of quiet (the reconnect replays missed events via last-event-id), and
  the poll guarantees state can never drift for more than one cycle.

Rate limits:
  The bridge handles roughly 10 light commands / 1 group command per
  second across ALL connected apps, rejects more than ~3 concurrent
  requests with HTTP 429, and may answer 503 when busy. The driver keeps
  a small connection pool and retries 429/503 briefly; don't drive
  continuous fades through REST (that's what the Hue Entertainment API is
  for — out of scope here).

Authentication:
  Per-app "application key" generated by POSTing to /api after the user
  presses the physical link button on the bridge. Run the "Pair with
  Bridge (Link Button)" setup action from the device page — it verifies
  the bridge, requests the key, saves it into the device config, and
  reconnects. The key is the standing credential and does not expire.
  All CLIP v2 requests are HTTPS; the bridge's certificate is issued by
  Signify's own CA (not in system trust stores), so verification is
  disabled — the same posture as the reference implementation.

Scope:
  AV-integrator runtime control surface — recall scenes, on/off rooms,
  set brightness / color / color-temperature on groups or individual
  lights (with optional transition times), monitor per-light
  reachability. Light/group/scene creation, sensor/rule/automation
  management, entertainment streaming, and software-update control are
  install-time tasks left to the Hue mobile app.
"""

from __future__ import annotations

import asyncio
import json
from typing import Any

import httpx

from server.drivers.base import BaseDriver, ConnectionFaultError
from server.utils.logger import get_logger

log = get_logger(__name__)

_DEVICETYPE = "openavc#openavc"

# Bridge-busy handling: the bridge 429s above ~3 concurrent requests and
# may 503 under load; retry briefly with linear backoff.
_BUSY_STATUSES = (429, 503)
_BUSY_RETRIES = 6
_BUSY_BACKOFF = 0.25

# Reopen the event stream after this much silence. The bridge sends NO
# keepalive on the stream, so a long-idle stream is indistinguishable from
# a dead one; a periodic reopen (with last-event-id replay) bounds how long
# a silently dead stream can linger. Cheap: a quiet bridge costs one HTTPS
# reconnect every 90 s.
_STREAM_IDLE_REOPEN_S = 90.0

# Shared per-light child props; capability props are added per light from
# the features its v2 resource actually carries.
_LIGHT_SHARED_SCHEMA: dict[str, dict[str, Any]] = {
    "name": {"type": "string", "label": "Name", "cloud_priority": "low"},
    "model": {"type": "string", "label": "Model", "cloud_priority": "low"},
    "on": {
        "type": "boolean",
        "label": "On",
        "control": True,
        "cloud_priority": "high",
    },
}

_GROUP_SCHEMA: dict[str, dict[str, Any]] = {
    "name": {"type": "string", "label": "Name", "cloud_priority": "low"},
    "type": {"type": "string", "label": "Group Type", "cloud_priority": "low"},
    "room_class": {"type": "string", "label": "Room Class", "cloud_priority": "low"},
    "on": {
        "type": "boolean",
        "label": "Any On",
        "control": True,
        "cloud_priority": "high",
    },
    "brightness": {
        "type": "number",
        "label": "Brightness (%)",
        "min": 0,
        "max": 100,
        "control": True,
        "cloud_priority": "low",
    },
    "lights": {"type": "string", "label": "Member Lights", "cloud_priority": "low"},
}

_TRANSITION_PARAM = {
    "type": "integer",
    "min": 0,
    "max": 6000000,
    "label": "Transition (ms)",
    "help": "Optional fade time in milliseconds (100 ms steps).",
}


def _light_param(required: bool = True) -> dict[str, Any]:
    return {
        "type": "child_id",
        "child_type": "light",
        "required": required,
        "label": "Light",
    }


def _group_param() -> dict[str, Any]:
    return {
        "type": "child_id",
        "child_type": "group",
        "required": True,
        "label": "Group",
    }


class PhilipsHueDriver(BaseDriver):
    """Philips Hue Bridge driver (CLIP API v2, SSE push)."""

    DRIVER_INFO = {
        "id": "philips_hue",
        "name": "Philips Hue Bridge",
        "manufacturer": "Signify",
        "category": "lighting",
        "version": "3.0.0",
        # HTTPS-only device: simulation needs the 0.23.0 redirect (ssl flip);
        # the SSE push generation ships in the same platform release.
        "min_platform_version": "0.23.0",
        "author": "OpenAVC",
        "description": (
            "Controls Philips Hue lights, rooms, zones, and scenes via the "
            "CLIP v2 API on a Hue Bridge (HTTPS). Live push state from the "
            "bridge's event stream; every light and group is a child entity; "
            "pair with the bridge's link button straight from the device "
            "page. Requires the square v2 bridge (BSB002)."
        ),
        "source_url": "https://github.com/home-assistant-libs/aiohue/tree/main/aiohue/v2",
        "tags": ["hue", "philips", "signify", "lighting", "residential", "bridge", "scenes"],
        "verified": True,
        "simulated": True,
        "protocols": ["hue_clip_v2"],
        "ports": [443],
        "compatible_models": [
            {
                "manufacturer": "Signify",
                "models": [
                    "Hue Bridge V2 (BSB002)",
                ],
                "confidence": "full",
                "notes": (
                    "Verified against a BSB002 bridge (firmware "
                    "1.78.1978074000): HTTPS + application-key connect, "
                    "enumeration of a 19-light install with rooms/zones/"
                    "scenes, live event-stream updates, and a light write "
                    "confirmed back over the stream. The CLIP v2 API "
                    "requires firmware 1948086000 or newer (any bridge "
                    "updated since late 2019). The link-button pairing "
                    "flow is unchanged from the previous driver "
                    "generation, which was verified on the same bridge."
                ),
            },
        ],
        "transport": "http",
        "help": {
            "overview": (
                "Philips Hue is the most widely deployed residential and "
                "small-commercial smart-lighting platform. The bridge sits "
                "on the LAN and bridges Zigbee bulbs / fixtures to a local "
                "REST API. AV integrators commonly use it for accent "
                "lighting in boardrooms, hospitality spaces, and houses of "
                "worship — recall a \"Presentation\" scene when the "
                "projector turns on, fade up \"Q&A\" lighting when the "
                "session ends.\n\n"
                "Every light and every group (room / zone, plus the "
                "whole-home \"All Lights\" group) appears as a child entity "
                "with live on/brightness/color state pushed by the bridge "
                "the moment it changes — including changes made from the "
                "Hue app or Hue dimmer switches. Scenes are offered in a "
                "picker on the recall command."
            ),
            "setup": (
                "1. Set a static IP (or DHCP reservation) on the Hue Bridge "
                "in your router. The bridge is also discoverable via mDNS.\n"
                "2. Add the device with the bridge's IP address, leaving "
                "the App Key blank.\n"
                "3. Press the round link button on top of the bridge, then "
                "run the \"Pair with Bridge (Link Button)\" action from "
                "this device's page within 30 seconds. It requests an app "
                "key, saves it, and reconnects automatically.\n"
                "4. Lights, groups, and scenes are enumerated on connect "
                "and stay in sync live — new fixtures added in the Hue app "
                "appear on their own.\n"
                "5. Commands that act on a light or group offer a picker of "
                "the discovered children; the recall command offers a scene "
                "picker. Brightness and color commands take an optional "
                "transition time for smooth fades."
            ),
        },
        "discovery": {
            # The bridge advertises _hue._tcp via mDNS; the OUI prefixes are
            # Philips / Signify. The active probe is the unauthenticated v1
            # GET /api/config (plain HTTP on 80) every Hue bridge answers
            # with its bridgeid — including v2-only installs; only the CLIP
            # v2 control surface itself is HTTPS-only.
            "mdns": "_hue._tcp.local.",
            "oui": [
                "00:17:88",
                "ec:b5:fa",
                "1c:53:f9",
            ],
            "tcp_probe": {
                "port": 80,
                "send_ascii": "GET /api/config HTTP/1.0\r\n\r\n",
                "expect": '"bridgeid"',
                "extract_manufacturer": "Signify",
                "extract": {
                    "model": {"regex": '"modelid"\\s*:\\s*"([^"]+)"', "group": 1},
                    "name": {"regex": '"name"\\s*:\\s*"([^"]+)"', "group": 1},
                },
            },
        },
        "default_config": {
            "host": "",
            # ssl/port are connection plumbing, not user settings: CLIP v2
            # is always HTTPS on 443. Declared so the simulation redirect
            # can flip them at the simulator (plain HTTP on a local port).
            "ssl": True,
            "port": 0,
            "app_key": "",
            "timeout": 5.0,
            "poll_interval": 30,
        },
        "config_schema": {
            "host": {
                "type": "string",
                "required": True,
                "label": "Bridge IP Address",
                "description": (
                    "IP address of the Hue Bridge. Set a DHCP reservation "
                    "in your router."
                ),
            },
            "app_key": {
                "type": "string",
                "default": "",
                "label": "App Key",
                "description": (
                    "Per-app authentication key. Leave blank and run the "
                    "\"Pair with Bridge (Link Button)\" action to generate "
                    "and save one."
                ),
                "secret": True,
            },
            "poll_interval": {
                "type": "integer",
                "default": 30,
                "min": 5,
                "label": "Resync Interval (sec)",
                "description": (
                    "How often to do a full state resync. Normal updates "
                    "arrive instantly over the bridge's event stream; this "
                    "is the safety net."
                ),
            },
            "timeout": {
                "type": "number",
                "default": 5.0,
                "label": "Request Timeout (sec)",
            },
        },
        "state_variables": {
            "bridge_name": {
                "type": "string",
                "label": "Bridge Name",
                "help": "Friendly bridge name configured in the Hue app.",
            },
            "bridge_id": {
                "type": "string",
                "label": "Bridge ID",
                "help": (
                    "16-character hex bridge identifier (also printed on "
                    "the bridge label)."
                ),
            },
            "model_id": {
                "type": "string",
                "label": "Model ID",
                "help": "Hue Bridge model code (BSB002).",
            },
            "sw_version": {
                "type": "string",
                "label": "Bridge Firmware Version",
                "help": "Bridge software version from the bridge's device record.",
            },
            "light_count": {
                "type": "integer",
                "label": "Lights",
                "help": "Number of lights enumerated from the bridge.",
            },
            "group_count": {
                "type": "integer",
                "label": "Groups",
                "help": (
                    "Number of rooms and zones defined on the bridge (the "
                    "whole-home All Lights group is not counted)."
                ),
            },
            "scene_count": {
                "type": "integer",
                "label": "Scenes",
                "help": "Number of scenes stored on the bridge.",
            },
            "scene_options": {
                "type": "string",
                "label": "Scene Options",
                "help": (
                    "JSON list of {value,label} scene entries. Populates "
                    "the scene picker on the recall command."
                ),
            },
            "last_error": {
                "type": "string",
                "label": "Last Error",
            },
        },
        "child_entity_types": {
            "light": {
                "label": "Light",
                "label_plural": "Lights",
                # Per-child schemas: each light exposes only the capability
                # features its v2 resource actually carries (an on/off plug
                # has no dimming; a white-ambiance light no color), and
                # color-temperature bounds come from the light's own
                # mirek_schema.
                "dynamic": True,
                "id_format": {"type": "string"},
                "state_variables": dict(_LIGHT_SHARED_SCHEMA),
                "summary_fields": ["name", "model", "on"],
                "label_field": "name",
            },
            "group": {
                "label": "Group",
                "label_plural": "Groups",
                "id_format": {"type": "string"},
                "state_variables": dict(_GROUP_SCHEMA),
                "summary_fields": ["name", "type", "on"],
                "label_field": "name",
            },
        },
        "device_settings": {
            "bridge_name": {
                "type": "string",
                "label": "Bridge Name",
                "help": (
                    "Friendly bridge name shown in the Hue app and mDNS. "
                    "Written to the bridge's device record and read back "
                    "from the resync."
                ),
                "state_key": "bridge_name",
                "default": "",
                "setup": False,
            },
        },
        "quick_actions": ["all_on", "all_off", "refresh"],
        "actions": [
            {"id": "all_on", "kind": "command", "icon": "sun"},
            {"id": "all_off", "kind": "command", "icon": "moon"},
            {"id": "refresh", "kind": "command", "icon": "refresh-cw"},
            {
                "id": "pair_bridge",
                "kind": "setup",
                "label": "Pair with Bridge (Link Button)",
                "icon": "link",
                "availability": "always",
                "params": {
                    "save": {
                        "type": "boolean",
                        "default": True,
                        "label": "Save app key and reconnect",
                    },
                },
            },
        ],
        "commands": {
            # ── Bridge-wide ──
            "refresh": {
                "label": "Refresh Lights & Groups",
                "params": {},
                "help": (
                    "Full resync from the bridge — re-enumerates lights, "
                    "groups, and scenes. Rarely needed: the event stream "
                    "keeps everything current on its own."
                ),
            },
            "query_full_state": {
                "label": "Query Full Bridge State",
                "params": {},
                "help": (
                    "Returns every resource on the bridge as raw JSON "
                    "(one GET /clip/v2/resource) and refreshes all "
                    "mirrored state."
                ),
            },
            "all_on": {
                "label": "All Lights On",
                "params": {},
                "help": "Turn every light on (the whole-home group).",
            },
            "all_off": {
                "label": "All Lights Off",
                "params": {},
                "help": "Turn every light off (the whole-home group).",
            },
            # ── Lights ──
            "light_on": {
                "label": "Light On",
                "params": {"light": _light_param()},
            },
            "light_off": {
                "label": "Light Off",
                "params": {"light": _light_param()},
            },
            "set_light_brightness": {
                "label": "Set Light Brightness",
                "params": {
                    "light": _light_param(),
                    "brightness": {
                        "type": "number",
                        "min": 1,
                        "max": 100,
                        "required": True,
                        "label": "Brightness (%)",
                        "help": (
                            "1-100. The bridge treats 0 as \"lowest "
                            "possible\"; use Light Off to switch off."
                        ),
                    },
                    "transition_ms": dict(_TRANSITION_PARAM),
                },
                "help": (
                    "Also turns the light on — the bridge rejects dimming "
                    "writes to a light that is off."
                ),
            },
            "set_light_ct": {
                "label": "Set Light Color Temperature",
                "params": {
                    "light": _light_param(),
                    "mirek": {
                        "type": "integer",
                        "min": 153,
                        "max": 500,
                        "required": True,
                        "label": "Color Temperature (mirek)",
                        "help": (
                            "153 (cool, ~6500 K) to 500 (warm, 2000 K). "
                            "Individual lights may support a narrower "
                            "range — see the light's own bounds."
                        ),
                    },
                    "transition_ms": dict(_TRANSITION_PARAM),
                },
                "help": "Also turns the light on.",
            },
            "set_light_xy": {
                "label": "Set Light Color (CIE xy)",
                "params": {
                    "light": _light_param(),
                    "x": {
                        "type": "number", "min": 0, "max": 1,
                        "required": True, "label": "CIE x",
                    },
                    "y": {
                        "type": "number", "min": 0, "max": 1,
                        "required": True, "label": "CIE y",
                    },
                    "transition_ms": dict(_TRANSITION_PARAM),
                },
                "help": "Also turns the light on.",
            },
            "light_identify": {
                "label": "Identify Light",
                "params": {"light": _light_param()},
                "help": (
                    "Makes the light breathe once so an installer can find "
                    "the fixture."
                ),
            },
            # ── Groups (rooms / zones / whole home) ──
            "group_on": {
                "label": "Group On",
                "params": {"group": _group_param()},
            },
            "group_off": {
                "label": "Group Off",
                "params": {"group": _group_param()},
            },
            "set_group_brightness": {
                "label": "Set Group Brightness",
                "params": {
                    "group": _group_param(),
                    "brightness": {
                        "type": "number",
                        "min": 1,
                        "max": 100,
                        "required": True,
                        "label": "Brightness (%)",
                    },
                    "transition_ms": dict(_TRANSITION_PARAM),
                },
                "help": "Also turns the group on.",
            },
            "set_group_ct": {
                "label": "Set Group Color Temperature",
                "params": {
                    "group": _group_param(),
                    "mirek": {
                        "type": "integer", "min": 153, "max": 500,
                        "required": True, "label": "Color Temperature (mirek)",
                    },
                    "transition_ms": dict(_TRANSITION_PARAM),
                },
                "help": (
                    "Applies to every color-temperature-capable light in "
                    "the group. Needs bridge firmware 1.50 or newer."
                ),
            },
            "set_group_xy": {
                "label": "Set Group Color (CIE xy)",
                "params": {
                    "group": _group_param(),
                    "x": {
                        "type": "number", "min": 0, "max": 1,
                        "required": True, "label": "CIE x",
                    },
                    "y": {
                        "type": "number", "min": 0, "max": 1,
                        "required": True, "label": "CIE y",
                    },
                    "transition_ms": dict(_TRANSITION_PARAM),
                },
                "help": (
                    "Applies to every color-capable light in the group. "
                    "Needs bridge firmware 1.50 or newer."
                ),
            },
            # ── Scenes ──
            "recall_scene": {
                "label": "Recall Scene",
                "params": {
                    "scene": {
                        "type": "string",
                        "required": True,
                        "label": "Scene",
                        "options_state": "scene_options",
                    },
                    "duration_ms": dict(_TRANSITION_PARAM),
                },
                "help": (
                    "Recalls a scene on its own room / zone. The optional "
                    "duration fades the scene in."
                ),
            },
        },
    }

    def __init__(self, *args: Any, **kwargs: Any) -> None:
        super().__init__(*args, **kwargs)
        self._client: httpx.AsyncClient | None = None
        self._app_key: str = ""
        # Last-known per-light schema (reconcile guard, dante/qsc pattern).
        self._light_schemas: dict[str, dict[str, Any]] = {}
        # Registered group ids (rooms + zones + the whole-home group).
        self._group_ids: set[str] = set()
        # group id -> its grouped_light service rid (write target).
        self._group_grouped_light: dict[str, str] = {}
        # grouped_light rid -> group id (event routing).
        self._grouped_light_owner: dict[str, str] = {}
        # light rid -> owner device rid; device rid -> light rid;
        # zigbee_connectivity rid -> owner device rid (reachability routing).
        self._light_device: dict[str, str] = {}
        self._device_light: dict[str, str] = {}
        self._connectivity_device: dict[str, str] = {}
        # The whole-home group id and the bridge's own device rid.
        self._home_id: str = ""
        self._bridge_device_rid: str = ""
        # SSE stream task + resume cursor.
        self._event_task: asyncio.Task | None = None
        self._last_event_id: str = ""
        self._roster_refresh_task: asyncio.Task | None = None

    # ── Connection lifecycle ──

    def _base_url(self) -> str:
        host = str(self.config.get("host", "")).strip()
        use_ssl = bool(self.config.get("ssl", True))
        scheme = "https" if use_ssl else "http"
        port = int(self.config.get("port", 0) or 0)
        default = 443 if use_ssl else 80
        if port in (0, default):
            return f"{scheme}://{host}"
        return f"{scheme}://{host}:{port}"

    async def connect(self) -> None:
        host = str(self.config.get("host", "")).strip()
        if not host:
            raise ConnectionError("Bridge IP address is required")
        self._app_key = str(self.config.get("app_key", "")).strip()

        # The bridge rejects >3 concurrent requests with 429 — keep the
        # pool at 3 (shared by polling, commands, and the event stream).
        self._client = httpx.AsyncClient(
            base_url=self._base_url(),
            timeout=float(self.config.get("timeout", 5.0)),
            verify=False,
            headers={"hue-application-key": self._app_key},
            limits=httpx.Limits(max_connections=3),
        )

        try:
            if not self._app_key:
                raise ConnectionFaultError(
                    "No app key configured — press the link button on the "
                    "bridge and run the \"Pair with Bridge\" setup action.",
                    code="auth_failed",
                )
            resources = await self._get_resources()
            self._reconcile(resources)
        except httpx.TransportError as exc:
            await self._close_client()
            raise ConnectionError(
                f"Could not reach the Hue Bridge at {host}: {exc}"
            ) from exc
        except Exception:
            await self._close_client()
            raise

        self._connected = True
        self.set_state("connected", True)
        self.set_state("last_error", None)
        await self.events.emit(f"device.connected.{self.device_id}")
        log.info(f"[{self.device_id}] Connected to Hue Bridge at {host}")

        # Live updates: one SSE stream carries every resource change.
        self._event_task = asyncio.create_task(self._event_loop())

        poll_interval = int(self.config.get("poll_interval", 30))
        if poll_interval > 0:
            await self.start_polling(poll_interval)

    async def disconnect(self) -> None:
        await self._stop_task("_event_task")
        await self._stop_task("_roster_refresh_task")
        await self.stop_polling()
        await self._close_client()
        self._connected = False
        self.set_state("connected", False)
        await self.events.emit(f"device.disconnected.{self.device_id}")
        log.info(f"[{self.device_id}] Disconnected from Hue Bridge")

    async def _stop_task(self, attr: str) -> None:
        task: asyncio.Task | None = getattr(self, attr)
        setattr(self, attr, None)
        if task is not None:
            task.cancel()
            try:
                await task
            except (asyncio.CancelledError, Exception):
                pass

    async def _close_client(self) -> None:
        if self._client:
            await self._client.aclose()
            self._client = None

    async def poll(self) -> None:
        """Full resync: one bulk fetch reconciles rosters and every value.
        Transport errors propagate so the platform watchdog can flip the
        device offline."""
        if not self._client:
            return
        try:
            self._reconcile(await self._get_resources())
        except httpx.TransportError as exc:
            raise ConnectionError(
                f"Hue Bridge not responding: {exc}"
            ) from exc

    # ── Request plumbing ──

    async def _request(self, method: str, path: str, body: Any = None) -> Any:
        """Send one CLIP v2 request and return the response's data list.

        Transport errors propagate to the caller. HTTP 401/403 (rejected /
        revoked app key) raises a typed auth_failed fault. 429/503 (bridge
        busy) is retried briefly with linear backoff, matching the bridge's
        documented concurrency behavior.
        """
        if not self._client:
            raise ConnectionError("Not connected")
        for attempt in range(_BUSY_RETRIES + 1):
            resp = await self._client.request(method, path, json=body)
            if resp.status_code not in _BUSY_STATUSES:
                break
            if attempt < _BUSY_RETRIES:
                await asyncio.sleep(_BUSY_BACKOFF * (attempt + 1))
        if resp.status_code in (401, 403):
            raise ConnectionFaultError(
                "The bridge rejected the app key — re-pair with the "
                "\"Pair with Bridge\" setup action.",
                code="auth_failed",
            )
        if resp.is_error:
            raise ConnectionError(
                f"Hue Bridge returned HTTP {resp.status_code} for {path}"
            )
        payload = resp.json()
        if not isinstance(payload, dict):
            raise ConnectionError(f"Unexpected response shape for {path}")
        errors = payload.get("errors") or []
        if errors:
            desc = str(
                (errors[0] or {}).get("description", "unknown error")
            )
            self.set_state("last_error", desc)
            raise ValueError(f"Bridge error: {desc}")
        return payload.get("data", [])

    async def _get_resources(self) -> list[dict[str, Any]]:
        """Bulk fetch: every resource on the bridge in one call."""
        return await self._request("GET", "/clip/v2/resource")

    # ── State mirroring ──

    @staticmethod
    def _name_of(res: dict[str, Any]) -> str:
        meta = res.get("metadata")
        if isinstance(meta, dict):
            return str(meta.get("name", ""))
        return ""

    def _light_schema_values(
        self,
        res: dict[str, Any],
        devices: dict[str, dict[str, Any]],
        reachable: dict[str, bool],
    ) -> tuple[dict[str, Any], dict[str, Any]]:
        """Return (schema, values) for one light from its v2 resource.

        The schema mirrors the light's real feature set — dimming /
        color_temperature / color appear only when the resource carries
        them, and mirek bounds come from the light's own mirek_schema — so
        an on/off plug never grows a brightness prop. The platform
        ``online`` mirrors the owner device's Zigbee connectivity.
        """
        owner_rid = str((res.get("owner") or {}).get("rid", ""))
        device = devices.get(owner_rid, {})
        product = (device.get("product_data") or {})
        schema: dict[str, dict[str, Any]] = {
            k: dict(v) for k, v in _LIGHT_SHARED_SCHEMA.items()
        }
        values: dict[str, Any] = {
            "name": self._name_of(res) or self._name_of(device),
            "model": str(product.get("product_name", "")),
            "on": bool((res.get("on") or {}).get("on", False)),
            "online": reachable.get(owner_rid, True),
        }
        dimming = res.get("dimming")
        if isinstance(dimming, dict):
            schema["brightness"] = {
                "type": "number",
                "label": "Brightness (%)",
                "min": 1,
                "max": 100,
                "control": True,
                "cloud_priority": "low",
            }
            values["brightness"] = round(float(dimming.get("brightness", 0.0)), 2)
        ct = res.get("color_temperature")
        if isinstance(ct, dict):
            mschema = ct.get("mirek_schema") or {}
            schema["mirek"] = {
                "type": "integer",
                "label": "Color Temperature (mirek)",
                "min": int(mschema.get("mirek_minimum", 153)),
                "max": int(mschema.get("mirek_maximum", 500)),
                "control": True,
                "cloud_priority": "low",
            }
            mirek = ct.get("mirek")
            values["mirek"] = int(mirek) if mirek is not None else 0
        color = res.get("color")
        if isinstance(color, dict):
            schema["xy"] = {
                "type": "string",
                "label": "XY (CIE)",
                "cloud_priority": "low",
            }
            values["xy"] = self._xy_string(color)
        return schema, values

    @staticmethod
    def _xy_string(color: dict[str, Any]) -> str:
        xy = color.get("xy") or {}
        try:
            return f"{float(xy.get('x', 0)):.4f},{float(xy.get('y', 0)):.4f}"
        except (TypeError, ValueError):
            return ""

    def _reconcile(self, resources: list[dict[str, Any]]) -> None:
        """Apply one bulk resource fetch: rosters, values, metadata, scenes."""
        by_type: dict[str, list[dict[str, Any]]] = {}
        for res in resources:
            if isinstance(res, dict):
                by_type.setdefault(str(res.get("type", "")), []).append(res)

        devices = {str(d.get("id")): d for d in by_type.get("device", [])}
        # Reachability: zigbee_connectivity resources belong to the light's
        # owner device; status "connected" = reachable.
        reachable: dict[str, bool] = {}
        self._connectivity_device.clear()
        for zc in by_type.get("zigbee_connectivity", []):
            owner = str((zc.get("owner") or {}).get("rid", ""))
            self._connectivity_device[str(zc.get("id"))] = owner
            reachable[owner] = str(zc.get("status", "")) == "connected"

        # Bridge identity lives across the bridge resource + its device.
        for bridge in by_type.get("bridge", []):
            self.set_state("bridge_id", str(bridge.get("bridge_id", "")))
            owner = str((bridge.get("owner") or {}).get("rid", ""))
            self._bridge_device_rid = owner
            bdev = devices.get(owner, {})
            product = bdev.get("product_data") or {}
            self.set_states({
                "bridge_name": self._name_of(bdev),
                "model_id": str(product.get("model_id", "")),
                "sw_version": str(product.get("software_version", "")),
            })

        # Lights (dynamic per-capability schemas).
        seen_lights: set[str] = set()
        self._light_device.clear()
        self._device_light.clear()
        for res in sorted(
            by_type.get("light", []), key=lambda r: self._name_of(r).lower()
        ):
            lid = str(res.get("id", ""))
            if not lid:
                continue
            seen_lights.add(lid)
            owner = str((res.get("owner") or {}).get("rid", ""))
            self._light_device[lid] = owner
            self._device_light[owner] = lid
            schema, values = self._light_schema_values(res, devices, reachable)
            prev = self._light_schemas.get(lid)
            if prev == schema and self.is_child_registered("light", lid):
                self.set_child_state_batch("light", lid, values)
            else:
                if self.is_child_registered("light", lid):
                    self.deregister_child("light", lid)
                self.register_child("light", lid, schema=schema, initial_state=values)
            self._light_schemas[lid] = schema
        for lid in list(self._light_schemas):
            if lid not in seen_lights:
                self.deregister_child("light", lid)
                self._light_schemas.pop(lid, None)
        self.set_state("light_count", len(seen_lights))

        # Groups: rooms + zones + the whole-home group. Each carries a
        # grouped_light service that holds its on/brightness state and is
        # the write target.
        grouped = {
            str(g.get("id")): g for g in by_type.get("grouped_light", [])
        }
        seen_groups: set[str] = set()
        group_names: dict[str, str] = {}
        self._group_grouped_light.clear()
        self._grouped_light_owner.clear()
        home_ids: set[str] = set()

        def _grouped_rid(res: dict[str, Any]) -> str:
            for svc in res.get("services") or []:
                if isinstance(svc, dict) and svc.get("rtype") == "grouped_light":
                    return str(svc.get("rid", ""))
            return ""

        def _member_lights(res: dict[str, Any]) -> str:
            names: list[str] = []
            for child in res.get("children") or []:
                if not isinstance(child, dict):
                    continue
                rid = str(child.get("rid", ""))
                if child.get("rtype") == "light":
                    # Zones group light services directly.
                    dev_rid = self._light_device.get(rid, "")
                    names.append(self._name_of(devices.get(dev_rid, {})) or rid)
                elif child.get("rtype") == "device":
                    # Rooms group devices; use the device name.
                    names.append(self._name_of(devices.get(rid, {})) or rid)
            return ", ".join(n for n in names if n)

        for gtype in ("room", "zone", "bridge_home"):
            for res in by_type.get(gtype, []):
                gid = str(res.get("id", ""))
                if not gid:
                    continue
                gl_rid = _grouped_rid(res)
                gl = grouped.get(gl_rid, {})
                name = self._name_of(res) or (
                    "All Lights" if gtype == "bridge_home" else ""
                )
                meta = res.get("metadata") or {}
                values = {
                    "name": name,
                    "type": "home" if gtype == "bridge_home" else gtype,
                    "room_class": str(meta.get("archetype", "")),
                    "on": bool((gl.get("on") or {}).get("on", False)),
                    "brightness": round(
                        float((gl.get("dimming") or {}).get("brightness", 0.0)), 2
                    ),
                    "lights": _member_lights(res),
                }
                seen_groups.add(gid)
                group_names[gid] = name
                if gtype == "bridge_home":
                    home_ids.add(gid)
                    self._home_id = gid
                if gl_rid:
                    self._group_grouped_light[gid] = gl_rid
                    self._grouped_light_owner[gl_rid] = gid
                if self.is_child_registered("group", gid):
                    self.set_child_state_batch("group", gid, values)
                else:
                    self.register_child("group", gid, initial_state=values)
                self._group_ids.add(gid)
        for gid in list(self._group_ids):
            if gid not in seen_groups:
                self.deregister_child("group", gid)
                self._group_ids.discard(gid)
        self.set_state(
            "group_count", len([g for g in seen_groups if g not in home_ids])
        )

        # Scenes: picker list only (a scene has no live state worth
        # mirroring; its group's lights carry the result).
        options: list[dict[str, str]] = []
        for res in by_type.get("scene", []):
            sid = str(res.get("id", ""))
            if not sid:
                continue
            label = self._name_of(res) or sid
            group_rid = str((res.get("group") or {}).get("rid", ""))
            group_name = group_names.get(group_rid)
            if group_name:
                label = f"{label} ({group_name})"
            options.append({"value": sid, "label": label})
        options.sort(key=lambda o: o["label"].lower())
        self.set_states({
            "scene_options": json.dumps(options),
            "scene_count": len(options),
        })

    async def _refresh_all(self) -> dict[str, int]:
        self._reconcile(await self._get_resources())
        return {
            "lights": len(self._light_schemas),
            "groups": len(self._group_ids),
            "scenes": int(self.get_state("scene_count") or 0),
        }

    async def refresh_children(self) -> dict[str, int]:
        """Backs the IDE "Refresh from Device" button."""
        if not self._client:
            raise ConnectionError(f"[{self.device_id}] Not connected")
        return await self._refresh_all()

    # ── Event stream (SSE push) ──

    async def _event_loop(self) -> None:
        """Hold the bridge's event stream open and apply events as they
        arrive.

        The bridge sends no keepalive, so the read times out after
        _STREAM_IDLE_REOPEN_S of silence and the stream is reopened —
        sending last-event-id so the bridge replays anything missed in the
        gap. Failures back off (2 s per consecutive attempt, capped) and
        never take the device down: polling remains the safety net, and a
        revoked app key surfaces as an auth fault through poll().
        """
        attempts = 0
        warned = False
        while self._client is not None:
            headers = {
                "Accept": "text/event-stream",
                "Cache-Control": "no-cache",
            }
            if self._last_event_id:
                headers["last-event-id"] = self._last_event_id
            try:
                timeout = httpx.Timeout(
                    connect=float(self.config.get("timeout", 5.0)),
                    read=_STREAM_IDLE_REOPEN_S,
                    write=float(self.config.get("timeout", 5.0)),
                    pool=None,
                )
                async with self._client.stream(
                    "GET", "/eventstream/clip/v2",
                    headers=headers, timeout=timeout,
                ) as response:
                    if response.status_code != 200:
                        await response.aread()
                        raise ConnectionError(
                            f"event stream rejected with HTTP "
                            f"{response.status_code}"
                        )
                    log.info(f"[{self.device_id}] Hue event stream open")
                    attempts = 0
                    warned = False
                    data_lines: list[str] = []
                    async for line in response.aiter_lines():
                        if line == "":
                            if data_lines:
                                self._apply_event_payload("\n".join(data_lines))
                                data_lines = []
                            continue
                        if line.startswith(":"):
                            continue
                        field, _, value = line.partition(":")
                        if value.startswith(" "):
                            value = value[1:]
                        if field == "data":
                            data_lines.append(value)
                        elif field == "id":
                            self._last_event_id = value.strip()
            except asyncio.CancelledError:
                raise
            except httpx.ReadTimeout:
                # Expected on a quiet bridge — reopen with last-event-id.
                log.debug(f"[{self.device_id}] Event stream idle; reopening")
                continue
            except Exception as exc:
                if self._client is None:
                    return
                attempts += 1
                msg = (
                    f"[{self.device_id}] Hue event stream failed "
                    f"({str(exc) or type(exc).__name__}); retrying"
                )
                if warned:
                    log.debug(msg)
                else:
                    log.warning(msg)
                    warned = True
                await asyncio.sleep(min(2.0 * attempts, 30.0))

    def _apply_event_payload(self, payload: str) -> None:
        """Apply one SSE data payload (a JSON array of event envelopes)."""
        try:
            envelopes = json.loads(payload)
        except (ValueError, TypeError):
            log.debug(f"[{self.device_id}] Unparseable event payload")
            return
        if not isinstance(envelopes, list):
            return
        roster_changed = False
        for env in envelopes:
            if not isinstance(env, dict):
                continue
            etype = str(env.get("type", ""))
            for res in env.get("data") or []:
                if not isinstance(res, dict):
                    continue
                if etype == "update":
                    self._apply_resource_update(res)
                elif etype in ("add", "delete"):
                    roster_changed = True
        if roster_changed:
            self._schedule_roster_refresh()

    def _apply_resource_update(self, res: dict[str, Any]) -> None:
        rtype = str(res.get("type", ""))
        rid = str(res.get("id", ""))
        if rtype == "light" and rid in self._light_schemas:
            values: dict[str, Any] = {}
            on = res.get("on")
            if isinstance(on, dict) and "on" in on:
                values["on"] = bool(on["on"])
            dimming = res.get("dimming")
            if isinstance(dimming, dict) and "brightness" in dimming:
                values["brightness"] = round(float(dimming["brightness"]), 2)
            ct = res.get("color_temperature")
            if isinstance(ct, dict) and ct.get("mirek") is not None:
                values["mirek"] = int(ct["mirek"])
            color = res.get("color")
            if isinstance(color, dict) and "xy" in color:
                values["xy"] = self._xy_string(color)
            meta = res.get("metadata")
            if isinstance(meta, dict) and meta.get("name"):
                values["name"] = str(meta["name"])
            if values:
                self.set_child_state_batch("light", rid, values)
        elif rtype == "grouped_light":
            gid = self._grouped_light_owner.get(rid)
            if not gid:
                return
            values = {}
            on = res.get("on")
            if isinstance(on, dict) and "on" in on:
                values["on"] = bool(on["on"])
            dimming = res.get("dimming")
            if isinstance(dimming, dict) and "brightness" in dimming:
                values["brightness"] = round(float(dimming["brightness"]), 2)
            if values:
                self.set_child_state_batch("group", gid, values)
        elif rtype == "zigbee_connectivity":
            owner = self._connectivity_device.get(rid) or str(
                (res.get("owner") or {}).get("rid", "")
            )
            lid = self._device_light.get(owner)
            if lid and "status" in res:
                self.set_child_state_batch(
                    "light", lid,
                    {"online": str(res.get("status")) == "connected"},
                )
        elif rtype == "device":
            meta = res.get("metadata")
            name = str(meta.get("name", "")) if isinstance(meta, dict) else ""
            if not name:
                return
            if rid == self._bridge_device_rid:
                self.set_state("bridge_name", name)
            lid = self._device_light.get(rid)
            if lid:
                self.set_child_state_batch("light", lid, {"name": name})

    def _schedule_roster_refresh(self) -> None:
        """Debounced full refresh after add/delete events (a new fixture
        pairs with several add events in a burst)."""
        if self._roster_refresh_task and not self._roster_refresh_task.done():
            return

        async def _refresh() -> None:
            await asyncio.sleep(2.0)
            try:
                await self._refresh_all()
            except Exception as exc:
                log.warning(
                    f"[{self.device_id}] Roster refresh after add/delete "
                    f"failed: {exc}"
                )

        self._roster_refresh_task = asyncio.create_task(_refresh())

    # ── Command surface ──

    @staticmethod
    def _with_transition(body: dict[str, Any], params: dict[str, Any],
                         key: str = "transition_ms") -> dict[str, Any]:
        raw = params.get(key)
        if raw not in (None, ""):
            body["dynamics"] = {"duration": int(raw)}
        return body

    async def send_command(self, command: str, params: dict[str, Any] | None = None) -> Any:
        params = params or {}
        if not self._client:
            raise ConnectionError(f"[{self.device_id}] Not connected")

        def light_path() -> str:
            return f"/clip/v2/resource/light/{params.get('light')}"

        def group_path() -> str:
            gid = str(params.get("group", ""))
            gl = self._group_grouped_light.get(gid)
            if not gl:
                raise ValueError(f"Unknown group: {gid}")
            return f"/clip/v2/resource/grouped_light/{gl}"

        match command:
            case "refresh":
                return await self._refresh_all()
            case "query_full_state":
                data = await self._get_resources()
                self._reconcile(data)
                return data
            case "all_on" | "all_off":
                gl = self._group_grouped_light.get(self._home_id)
                if not gl:
                    raise ValueError("The bridge reported no whole-home group")
                return await self._request(
                    "PUT", f"/clip/v2/resource/grouped_light/{gl}",
                    {"on": {"on": command == "all_on"}},
                )
            case "light_on":
                return await self._request(
                    "PUT", light_path(), {"on": {"on": True}}
                )
            case "light_off":
                return await self._request(
                    "PUT", light_path(), {"on": {"on": False}}
                )
            case "set_light_brightness":
                body = self._with_transition({
                    "on": {"on": True},
                    "dimming": {"brightness": float(params.get("brightness", 100))},
                }, params)
                return await self._request("PUT", light_path(), body)
            case "set_light_ct":
                body = self._with_transition({
                    "on": {"on": True},
                    "color_temperature": {"mirek": int(params.get("mirek", 300))},
                }, params)
                return await self._request("PUT", light_path(), body)
            case "set_light_xy":
                body = self._with_transition({
                    "on": {"on": True},
                    "color": {"xy": {
                        "x": float(params.get("x", 0.0)),
                        "y": float(params.get("y", 0.0)),
                    }},
                }, params)
                return await self._request("PUT", light_path(), body)
            case "light_identify":
                lid = str(params.get("light", ""))
                device_rid = self._light_device.get(lid)
                if not device_rid:
                    raise ValueError(f"Unknown light: {lid}")
                return await self._request(
                    "PUT", f"/clip/v2/resource/device/{device_rid}",
                    {"identify": {"action": "identify"}},
                )
            case "group_on":
                return await self._request(
                    "PUT", group_path(), {"on": {"on": True}}
                )
            case "group_off":
                return await self._request(
                    "PUT", group_path(), {"on": {"on": False}}
                )
            case "set_group_brightness":
                body = self._with_transition({
                    "on": {"on": True},
                    "dimming": {"brightness": float(params.get("brightness", 100))},
                }, params)
                return await self._request("PUT", group_path(), body)
            case "set_group_ct":
                body = self._with_transition({
                    "color_temperature": {"mirek": int(params.get("mirek", 300))},
                }, params)
                return await self._request("PUT", group_path(), body)
            case "set_group_xy":
                body = self._with_transition({
                    "color": {"xy": {
                        "x": float(params.get("x", 0.0)),
                        "y": float(params.get("y", 0.0)),
                    }},
                }, params)
                return await self._request("PUT", group_path(), body)
            case "recall_scene":
                sid = str(params.get("scene", ""))
                recall: dict[str, Any] = {"action": "active"}
                raw = params.get("duration_ms")
                if raw not in (None, ""):
                    recall["duration"] = int(raw)
                return await self._request(
                    "PUT", f"/clip/v2/resource/scene/{sid}",
                    {"recall": recall},
                )
            case _:
                raise ValueError(f"Unknown command: {command}")

    # ── Device settings ──

    async def set_device_setting(self, key: str, value: Any) -> Any:
        if key != "bridge_name":
            raise NotImplementedError(f"Unknown device setting: {key}")
        if not self._client:
            raise ConnectionError(f"[{self.device_id}] Not connected")
        name = str(value).strip()
        if not name:
            raise ValueError("Bridge name cannot be empty")
        if not self._bridge_device_rid:
            raise ConnectionError("Bridge device record not enumerated yet")
        await self._request(
            "PUT", f"/clip/v2/resource/device/{self._bridge_device_rid}",
            {"metadata": {"name": name}},
        )
        self.set_state("bridge_name", name)
        return name

    # ── Setup wizard: pair with the bridge's link button ──

    async def run_setup_action(
        self, action_id: str, params: dict[str, Any], progress: Any
    ) -> dict[str, Any]:
        """Pair with the bridge (out-of-band; runs while the device is
        offline). Verifies a Hue bridge answers at the configured host,
        requests an app key (the user must have pressed the link button),
        and optionally saves the key + reconnects.

        App-key creation is still the v1 POST /api endpoint — there is no
        v2 pairing call. The bridge-identity check uses the unauthenticated
        v1 GET /api/config, which every bridge answers.
        """
        if action_id != "pair_bridge":
            raise ValueError(f"Unknown setup action: {action_id}")

        host = str(self.config.get("host", "")).strip()
        if not host:
            raise ValueError("No bridge IP address configured")
        save = bool(params.get("save", True))

        async with httpx.AsyncClient(
            base_url=self._base_url(),
            timeout=float(self.config.get("timeout", 5.0)),
            verify=False,
        ) as client:
            await progress(f"Checking the bridge at {host}…", 10)
            try:
                resp = await client.get("/api/config")
            except httpx.TransportError as exc:
                raise ConnectionError(
                    f"Could not reach a Hue Bridge at {host}: {exc}"
                ) from exc
            info = resp.json() if resp.status_code == 200 else {}
            if not isinstance(info, dict) or "bridgeid" not in info:
                raise ConnectionError(
                    f"The device at {host} answered, but does not look like "
                    f"a Hue Bridge (no bridgeid in /api/config)."
                )

            await progress(
                "Requesting an app key — the link button must have been "
                "pressed within the last 30 seconds…",
                40,
            )
            resp = await client.post("/api", json={"devicetype": _DEVICETYPE})
            data = resp.json() if resp.status_code == 200 else []
            username = ""
            for entry in data if isinstance(data, list) else []:
                if not isinstance(entry, dict):
                    continue
                err = entry.get("error")
                if isinstance(err, dict):
                    if err.get("type") == 101:
                        raise ConnectionError(
                            "The bridge's link button has not been pressed. "
                            "Press the round button on top of the bridge, "
                            "then run this action again within 30 seconds."
                        )
                    raise ConnectionError(
                        f"Pairing failed: {err.get('description', 'unknown error')}"
                    )
                success = entry.get("success")
                if isinstance(success, dict) and success.get("username"):
                    username = str(success["username"])
            if not username:
                raise ConnectionError(
                    "The bridge did not return an app key. Retry after "
                    "pressing the link button."
                )

        saved = False
        if save:
            # The app key is the bridge's standing credential — persist it
            # so every future connect uses it.
            await self.request_config_update({"app_key": username})
            saved = True
            await progress("Reconnecting with the new app key…", 90)
            await self.request_reconnect()
        await progress("Done", 100)

        return {
            "paired": True,
            "bridge_name": str(info.get("name", "")),
            "bridge_id": str(info.get("bridgeid", "")),
            "app_key": username,
            "saved": saved,
        }
