"""
OpenAVC Philips Hue Bridge Driver (Local REST API V1).

Controls Philips Hue lights, groups (rooms / zones / "all lights"), and
scenes via the local REST API V1 on a Hue Bridge over HTTP (port 80).

Why Python (was YAML through v1.1.x):
  A Hue Bridge is inherently a many-unit controller — one bridge drives up
  to 50+ lights and dozens of rooms/zones, all keyed by per-install IDs.
  The YAML driver could only expose bridge metadata and blind per-ID
  commands; Python unlocks the parts that need code:
    - every light and group becomes a child entity enumerated from the
      bridge, each light with a per-child schema matching its real
      capability set (an on/off plug shows no brightness field, a
      white-ambiance light no hue/sat);
    - a "Pair with Bridge" setup wizard that runs while the device is
      OFFLINE — the old create_user command was unreachable in exactly the
      situation it existed for (no app key means the driver can't connect,
      and commands need a connected device);
    - nested-JSON parsing for rosters and state (the YAML driver matched
      flat config fields with regexes and could not fan a lights document
      out into per-light state);
    - typed connection faults (a rejected or missing app key shows as
      "authentication failed" on the device card, not a generic offline).

Models covered:
  - Hue Bridge V2 (BSB002, square)  — current production bridge
  - Hue Bridge V1 (BSB001, round)   — legacy, still supported by V1 API

Protocol reference:
  The Hue API V1 reference is gated behind a developer-portal login. This
  driver is built against the home-assistant-libs/aiohue V1 implementation
  (a mature open-source client that mirrors the original Signify spec).
  Facts verified there: the full-state document shape (GET /api/<key>),
  group 0 being excluded from GET /groups (fetched via /groups/0), the
  error taxonomy (type 1 = unauthorized, type 101 = link button not
  pressed, HTTP 403 = unauthorized), app-key creation (POST /api with a
  devicetype), and the unauthenticated GET /api/config discovery probe
  (aiohue's own is_hue_bridge check). The bridge rename write
  (PUT /api/<key>/config {"name": ...}) is confirmed against phue (MIT).

Push vs. poll:
  The V1 API is request/response only — there is no push or subscription
  primitive. (V2 / CLIP V2 adds Server-Sent Events over HTTPS; that is a
  separate driver effort.) This driver polls lights + groups every cycle
  and bridge config + scenes on a slower cadence. Light PUTs apply the
  bridge's per-field success confirmations to child state immediately;
  group PUTs and scene recalls trigger a lights+groups re-read because
  they fan out to member lights the confirmation doesn't enumerate.

Authentication:
  Per-app "username" (app key) generated by POSTing to /api after the user
  presses the physical link button on the bridge. Run the "Pair with
  Bridge (Link Button)" setup action from the device page — it verifies
  the bridge, requests the key, saves it into the device config, and
  reconnects. The key is the standing credential, so persisting it is
  correct.

Scope:
  AV-integrator runtime control surface — recall scenes, on/off rooms,
  set brightness / color / color-temperature on groups or individual
  lights, monitor per-light reachability. Light/group/scene creation,
  sensor/rule/schedule management, and software-update control are
  install-time tasks left to the Hue mobile app.
"""

from __future__ import annotations

import json
import re
from typing import Any

import httpx

from server.drivers.base import BaseDriver, ConnectionFaultError
from server.utils.logger import get_logger

log = get_logger(__name__)

# Bridge metadata fields mirrored from /api/<key>/config into flat state.
_CONFIG_FIELDS = {
    "name": "bridge_name",
    "bridgeid": "bridge_id",
    "modelid": "model_id",
    "apiversion": "api_version",
    "swversion": "sw_version",
    "mac": "mac_address",
    "zigbeechannel": "zigbee_channel",
}

# Refresh bridge config + scenes every Nth poll cycle (lights + groups
# refresh every cycle).
_METADATA_POLL_EVERY = 6

_DEVICETYPE = "openavc#openavc"

# PUT success confirmations address the exact field they changed.
_LIGHT_SUCCESS_RE = re.compile(r"^/lights/(\d+)/state/(\w+)$")
_GROUP_SUCCESS_RE = re.compile(r"^/groups/(\d+)/action/(\w+)$")

# Shared per-light child props; capability props are added per light from
# the fields its state document actually carries.
_LIGHT_SHARED_SCHEMA: dict[str, dict[str, Any]] = {
    "name": {"type": "string", "label": "Name", "cloud_priority": "low"},
    "type": {"type": "string", "label": "Light Type", "cloud_priority": "low"},
    "model": {"type": "string", "label": "Model", "cloud_priority": "low"},
    "on": {
        "type": "boolean",
        "label": "On",
        "control": True,
        "cloud_priority": "high",
    },
}

_LIGHT_CAPABILITY_SCHEMA: dict[str, dict[str, Any]] = {
    "bri": {
        "type": "integer",
        "label": "Brightness",
        "min": 1,
        "max": 254,
        "control": True,
        "cloud_priority": "low",
    },
    "ct": {
        "type": "integer",
        "label": "Color Temperature (mired)",
        "min": 153,
        "max": 500,
        "control": True,
        "cloud_priority": "low",
    },
    "hue": {
        "type": "integer",
        "label": "Hue",
        "min": 0,
        "max": 65535,
        "control": True,
        "cloud_priority": "low",
    },
    "sat": {
        "type": "integer",
        "label": "Saturation",
        "min": 0,
        "max": 254,
        "control": True,
        "cloud_priority": "low",
    },
    "xy": {"type": "string", "label": "XY (CIE)", "cloud_priority": "low"},
    "colormode": {"type": "string", "label": "Color Mode", "cloud_priority": "low"},
}


class PhilipsHueDriver(BaseDriver):
    """Philips Hue Bridge driver (local REST API V1)."""

    DRIVER_INFO = {
        "id": "philips_hue",
        "name": "Philips Hue Bridge",
        "manufacturer": "Signify",
        "category": "lighting",
        "version": "2.0.1",
        # Typed connection faults (ConnectionFaultError) landed in 0.22.0;
        # dynamic per-child schemas (0.19.4) are covered by the same gate.
        "min_platform_version": "0.22.0",
        "author": "OpenAVC",
        "description": (
            "Controls Philips Hue lights, rooms, zones, and scenes via the "
            "local REST API V1 on a Hue Bridge (HTTP, port 80). Every light "
            "and group is a child entity with live state; pair with the "
            "bridge's link button straight from the device page."
        ),
        "source_url": "https://github.com/home-assistant-libs/aiohue/tree/master/aiohue/v1",
        "tags": ["hue", "philips", "signify", "lighting", "residential", "bridge", "scenes"],
        "verified": True,
        "simulated": True,
        "protocols": ["hue_v1"],
        "ports": [80],
        "compatible_models": [
            {
                "manufacturer": "Signify",
                "models": [
                    "Hue Bridge V2 (BSB002)",
                ],
                "confidence": "full",
                "notes": (
                    "Verified against a BSB002 bridge (API 1.77.0): discovery "
                    "probe, link-button pairing wizard, light/group/scene "
                    "enumeration, and control. The V2 bridge also supports "
                    "the V2 / CLIP V2 API over HTTPS — this driver targets "
                    "V1 only."
                ),
            },
            {
                "manufacturer": "Signify",
                "models": [
                    "Hue Bridge V1 (BSB001)",
                ],
                "confidence": "untested",
                "notes": (
                    "Exposes the same V1 REST API on port 80. End-of-life "
                    "for new firmware but still functional."
                ),
            },
        ],
        "transport": "http",
        "help": {
            "overview": (
                "Philips Hue is the most widely deployed residential and "
                "small-commercial smart-lighting platform. The bridge sits "
                "on the LAN and bridges Zigbee bulbs / fixtures to a local "
                "REST API. AV integrators commonly use it for accent "
                "lighting in boardrooms, hospitality spaces, and houses of "
                "worship — recall a \"Presentation\" scene when the "
                "projector turns on, fade up \"Q&A\" lighting when the "
                "session ends.\n\n"
                "Every light and every group (room / zone, plus the special "
                "\"all lights\" group 0) appears as a child entity with "
                "live on/brightness/color state, so bindings, macros, and "
                "triggers can react to individual lights. Scenes are "
                "offered in a picker on the recall commands."
            ),
            "setup": (
                "1. Set a static IP (or DHCP reservation) on the Hue Bridge "
                "in your router. The bridge is also discoverable via mDNS.\n"
                "2. Add the device with the bridge's IP address, leaving "
                "the App Key blank.\n"
                "3. Press the round link button on top of the bridge, then "
                "run the \"Pair with Bridge (Link Button)\" action from "
                "this device's page within 30 seconds. It requests an app "
                "key, saves it, and reconnects automatically.\n"
                "4. Lights, groups, and scenes are enumerated on connect. "
                "Use \"Refresh from Device\" (or the refresh command) after "
                "adding fixtures in the Hue app.\n"
                "5. Commands that act on a light or group offer a picker of "
                "the discovered children; scene commands offer a scene "
                "picker."
            ),
        },
        "discovery": {
            # The bridge advertises _hue._tcp via mDNS; the OUI prefixes are
            # Philips / Signify. The active probe is the unauthenticated
            # GET /api/config every Hue bridge answers with its bridgeid
            # (the same check aiohue's is_hue_bridge uses).
            "mdns": "_hue._tcp.local.",
            "oui": [
                "00:17:88",
                "ec:b5:fa",
                "1c:53:f9",
            ],
            "tcp_probe": {
                "port": 80,
                "send_ascii": "GET /api/config HTTP/1.0\r\n\r\n",
                "expect": '"bridgeid"',
                "extract_manufacturer": "Signify",
                "extract": {
                    "model": {"regex": '"modelid"\\s*:\\s*"([^"]+)"', "group": 1},
                    "name": {"regex": '"name"\\s*:\\s*"([^"]+)"', "group": 1},
                },
            },
        },
        "default_config": {
            "host": "",
            "port": 80,
            "app_key": "",
            "timeout": 5.0,
            "poll_interval": 10,
        },
        "config_schema": {
            "host": {
                "type": "string",
                "required": True,
                "label": "Bridge IP Address",
                "description": (
                    "IP address of the Hue Bridge. Set a DHCP reservation "
                    "in your router."
                ),
            },
            "port": {
                "type": "integer",
                "default": 80,
                "label": "HTTP Port",
                "description": (
                    "V1 API port. Default 80. The bridge does not expose "
                    "V1 on HTTPS."
                ),
            },
            "app_key": {
                "type": "string",
                "default": "",
                "label": "App Key (Username)",
                "description": (
                    "Per-app authentication key. Leave blank and run the "
                    "\"Pair with Bridge (Link Button)\" action to generate "
                    "and save one."
                ),
                "secret": True,
            },
            "poll_interval": {
                "type": "integer",
                "default": 10,
                "min": 2,
                "label": "Poll Interval (sec)",
                "description": (
                    "How often to refresh light and group state. Bridge "
                    "metadata and scenes refresh on a slower cadence."
                ),
            },
            "timeout": {
                "type": "number",
                "default": 5.0,
                "label": "Request Timeout (sec)",
            },
        },
        "state_variables": {
            "bridge_name": {
                "type": "string",
                "label": "Bridge Name",
                "help": "Friendly bridge name configured in the Hue app.",
            },
            "bridge_id": {
                "type": "string",
                "label": "Bridge ID",
                "help": (
                    "16-character hex bridge identifier (also printed on "
                    "the bridge label)."
                ),
            },
            "model_id": {
                "type": "string",
                "label": "Model ID",
                "help": "Hue Bridge model code — BSB002 = V2 (square), BSB001 = V1 (round).",
            },
            "api_version": {
                "type": "string",
                "label": "API Version",
                "help": "Hue API version string reported by the bridge.",
            },
            "sw_version": {
                "type": "string",
                "label": "Bridge Firmware Version",
                "help": "Bridge firmware version (`swversion` field from /api/<user>/config).",
            },
            "mac_address": {
                "type": "string",
                "label": "MAC Address",
                "help": "Bridge MAC address (`mac` field from /api/<user>/config).",
            },
            "zigbee_channel": {
                "type": "integer",
                "label": "Zigbee Channel",
                "help": "ZigBee radio channel the bridge is currently using (11-26).",
            },
            "light_count": {
                "type": "integer",
                "label": "Lights",
                "help": "Number of lights enumerated from the bridge.",
            },
            "group_count": {
                "type": "integer",
                "label": "Groups",
                "help": (
                    "Number of rooms / zones / groups defined on the bridge "
                    "(the special all-lights group 0 is not counted)."
                ),
            },
            "scene_count": {
                "type": "integer",
                "label": "Scenes",
                "help": "Number of scenes stored on the bridge.",
            },
            "scene_options": {
                "type": "string",
                "label": "Scene Options",
                "help": (
                    "JSON list of {value,label} scene entries. Populates "
                    "the scene pickers on the recall commands."
                ),
            },
            "last_error": {
                "type": "string",
                "label": "Last Error",
            },
        },
        "child_entity_types": {
            "light": {
                "label": "Light",
                "label_plural": "Lights",
                # Per-child schemas: each light exposes only the capability
                # fields its state document actually carries (an on/off
                # plug has no bri; a white-ambiance light no hue/sat).
                "dynamic": True,
                "id_format": {"type": "integer", "min": 1, "pad_width": 2},
                "state_variables": dict(_LIGHT_SHARED_SCHEMA),
                "summary_fields": ["name", "type", "on"],
                "label_field": "name",
            },
            "group": {
                "label": "Group",
                "label_plural": "Groups",
                # min 0: group 0 is the bridge's special all-lights group
                # (excluded from GET /groups; fetched via /groups/0).
                "id_format": {"type": "integer", "min": 0, "pad_width": 2},
                "state_variables": {
                    "name": {"type": "string", "label": "Name", "cloud_priority": "low"},
                    "type": {"type": "string", "label": "Group Type", "cloud_priority": "low"},
                    "room_class": {"type": "string", "label": "Room Class", "cloud_priority": "low"},
                    "any_on": {"type": "boolean", "label": "Any On", "cloud_priority": "high"},
                    "all_on": {"type": "boolean", "label": "All On", "cloud_priority": "high"},
                    "bri": {"type": "integer", "label": "Brightness", "cloud_priority": "low"},
                    "lights": {"type": "string", "label": "Member Light IDs", "cloud_priority": "low"},
                },
                "summary_fields": ["name", "type", "any_on"],
                "label_field": "name",
            },
        },
        "device_settings": {
            "bridge_name": {
                "type": "string",
                "label": "Bridge Name",
                "help": (
                    "Friendly bridge name shown in the Hue app and mDNS. "
                    "Written via PUT /config and read back from the config "
                    "poll."
                ),
                "state_key": "bridge_name",
                "default": "",
                "setup": False,
            },
        },
        "quick_actions": ["all_on", "all_off", "refresh"],
        "actions": [
            {"id": "all_on", "kind": "command", "icon": "sun"},
            {"id": "all_off", "kind": "command", "icon": "moon"},
            {"id": "refresh", "kind": "command", "icon": "refresh-cw"},
            {
                "id": "pair_bridge",
                "kind": "setup",
                "label": "Pair with Bridge (Link Button)",
                "icon": "link",
                "availability": "always",
                "params": {
                    "save": {
                        "type": "boolean",
                        "default": True,
                        "label": "Save app key and reconnect",
                    },
                },
            },
        ],
        "commands": {
            # ── Pairing / bridge metadata ──
            "create_user": {
                "label": "Create User (Pair)",
                "params": {},
                "help": (
                    "Press the link button on top of the bridge, then run "
                    "this within 30 seconds. Returns the new app key. "
                    "Prefer the \"Pair with Bridge\" setup action — it also "
                    "saves the key and reconnects, and works while the "
                    "device is offline."
                ),
            },
            "query_config": {
                "label": "Query Bridge Config",
                "params": {},
                "help": "Refreshes bridge metadata state variables.",
            },
            "query_full_state": {
                "label": "Query Full Bridge State",
                "params": {},
                "help": (
                    "Re-reads the entire bridge state (config, lights, "
                    "groups, scenes) and reconciles all children. Returns "
                    "the raw JSON document for inspection."
                ),
            },
            "refresh": {
                "label": "Refresh Lights & Groups",
                "params": {},
                "help": (
                    "Re-enumerate lights, groups, and scenes from the "
                    "bridge and reconcile the child entities."
                ),
            },
            # ── Light commands (per-light children) ──
            "light_on": {
                "label": "Light On",
                "params": {
                    "light_id": {
                        "type": "child_id",
                        "child_type": "light",
                        "required": True,
                        "label": "Light",
                    },
                },
            },
            "light_off": {
                "label": "Light Off",
                "params": {
                    "light_id": {
                        "type": "child_id",
                        "child_type": "light",
                        "required": True,
                        "label": "Light",
                    },
                },
            },
            "light_set_brightness": {
                "label": "Light Set Brightness",
                "params": {
                    "light_id": {
                        "type": "child_id",
                        "child_type": "light",
                        "required": True,
                        "label": "Light",
                    },
                    "bri": {
                        "type": "integer",
                        "required": True,
                        "default": 254,
                        "min": 1,
                        "max": 254,
                        "label": "Brightness (1..254)",
                    },
                },
                "help": (
                    "Brightness 1..254. The light is turned on in the same "
                    "request (the bridge rejects brightness writes to an "
                    "off light)."
                ),
            },
            "light_set_color_temp": {
                "label": "Light Set Color Temperature",
                "params": {
                    "light_id": {
                        "type": "child_id",
                        "child_type": "light",
                        "required": True,
                        "label": "Light",
                    },
                    "ct": {
                        "type": "integer",
                        "required": True,
                        "default": 366,
                        "min": 153,
                        "max": 500,
                        "label": "Color Temperature (153..500 mired)",
                    },
                },
                "help": (
                    "Color temperature in mired (reciprocal megakelvin). "
                    "153 (~6500K, cool) to 500 (~2000K, warm). White-"
                    "ambiance and color lights only."
                ),
            },
            "light_set_hue_sat": {
                "label": "Light Set Hue / Saturation",
                "params": {
                    "light_id": {
                        "type": "child_id",
                        "child_type": "light",
                        "required": True,
                        "label": "Light",
                    },
                    "hue": {
                        "type": "integer",
                        "required": True,
                        "default": 0,
                        "min": 0,
                        "max": 65535,
                        "label": "Hue (0..65535)",
                    },
                    "sat": {
                        "type": "integer",
                        "required": True,
                        "default": 254,
                        "min": 0,
                        "max": 254,
                        "label": "Saturation (0..254)",
                    },
                },
                "help": "Color lights only.",
            },
            "light_set_xy": {
                "label": "Light Set XY (CIE)",
                "params": {
                    "light_id": {
                        "type": "child_id",
                        "child_type": "light",
                        "required": True,
                        "label": "Light",
                    },
                    "x": {
                        "type": "number",
                        "required": True,
                        "default": 0.3127,
                        "min": 0.0,
                        "max": 1.0,
                        "label": "X (0.0..1.0)",
                    },
                    "y": {
                        "type": "number",
                        "required": True,
                        "default": 0.329,
                        "min": 0.0,
                        "max": 1.0,
                        "label": "Y (0.0..1.0)",
                    },
                },
                "help": "CIE 1931 XY chromaticity coordinates. Color lights only.",
            },
            "light_alert": {
                "label": "Light Alert (Identify)",
                "params": {
                    "light_id": {
                        "type": "child_id",
                        "child_type": "light",
                        "required": True,
                        "label": "Light",
                    },
                    "alert": {
                        "type": "enum",
                        "values": ["none", "select", "lselect"],
                        "default": "select",
                        "required": True,
                        "label": "Alert Type",
                    },
                },
                "help": (
                    "Make the light flash so the installer can find it. "
                    "'select' = one breathe cycle, 'lselect' = breathe for "
                    "15 seconds, 'none' = stop."
                ),
            },
            "query_light": {
                "label": "Query Light",
                "params": {
                    "light_id": {
                        "type": "child_id",
                        "child_type": "light",
                        "required": True,
                        "label": "Light",
                    },
                },
                "help": "Returns the light's raw JSON and refreshes its child state.",
            },
            "query_all_lights": {
                "label": "Query All Lights",
                "params": {},
                "help": (
                    "Returns all lights as raw JSON and reconciles the "
                    "light children."
                ),
            },
            # ── Group commands (rooms / zones, group 0 = all lights) ──
            "group_on": {
                "label": "Group On",
                "params": {
                    "group_id": {
                        "type": "child_id",
                        "child_type": "group",
                        "required": True,
                        "label": "Group",
                    },
                },
            },
            "group_off": {
                "label": "Group Off",
                "params": {
                    "group_id": {
                        "type": "child_id",
                        "child_type": "group",
                        "required": True,
                        "label": "Group",
                    },
                },
            },
            "group_set_brightness": {
                "label": "Group Set Brightness",
                "params": {
                    "group_id": {
                        "type": "child_id",
                        "child_type": "group",
                        "required": True,
                        "label": "Group",
                    },
                    "bri": {
                        "type": "integer",
                        "required": True,
                        "default": 254,
                        "min": 1,
                        "max": 254,
                        "label": "Brightness (1..254)",
                    },
                },
            },
            "group_set_color_temp": {
                "label": "Group Set Color Temperature",
                "params": {
                    "group_id": {
                        "type": "child_id",
                        "child_type": "group",
                        "required": True,
                        "label": "Group",
                    },
                    "ct": {
                        "type": "integer",
                        "required": True,
                        "default": 366,
                        "min": 153,
                        "max": 500,
                        "label": "Color Temperature (153..500 mired)",
                    },
                },
            },
            "group_set_hue_sat": {
                "label": "Group Set Hue / Saturation",
                "params": {
                    "group_id": {
                        "type": "child_id",
                        "child_type": "group",
                        "required": True,
                        "label": "Group",
                    },
                    "hue": {
                        "type": "integer",
                        "required": True,
                        "default": 0,
                        "min": 0,
                        "max": 65535,
                        "label": "Hue (0..65535)",
                    },
                    "sat": {
                        "type": "integer",
                        "required": True,
                        "default": 254,
                        "min": 0,
                        "max": 254,
                        "label": "Saturation (0..254)",
                    },
                },
            },
            "group_recall_scene": {
                "label": "Group Recall Scene",
                "params": {
                    "group_id": {
                        "type": "child_id",
                        "child_type": "group",
                        "required": True,
                        "label": "Group",
                        "description": "Group 0 applies the scene to whichever lights it contains.",
                    },
                    "scene_id": {
                        "type": "string",
                        "required": True,
                        "label": "Scene",
                        "options_state": "scene_options",
                        "help": (
                            "Scene to recall, scoped to the group. Pick "
                            "from the discovered scenes or type a scene ID."
                        ),
                    },
                },
            },
            "query_group": {
                "label": "Query Group",
                "params": {
                    "group_id": {
                        "type": "child_id",
                        "child_type": "group",
                        "required": True,
                        "label": "Group",
                    },
                },
                "help": "Returns the group's raw JSON and refreshes its child state.",
            },
            "query_all_groups": {
                "label": "Query All Groups",
                "params": {},
                "help": (
                    "Returns all groups (rooms, zones, custom groups) as "
                    "raw JSON and reconciles the group children."
                ),
            },
            "all_on": {
                "label": "All Lights On",
                "params": {},
                "help": "Turn every light on (group 0).",
            },
            "all_off": {
                "label": "All Lights Off",
                "params": {},
                "help": "Turn every light off (group 0).",
            },
            # ── Scene commands ──
            "recall_scene": {
                "label": "Recall Scene (All Lights)",
                "params": {
                    "scene_id": {
                        "type": "string",
                        "required": True,
                        "label": "Scene",
                        "options_state": "scene_options",
                    },
                },
                "help": (
                    "Shortcut: recall a scene targeting group 0. Same as "
                    "Group Recall Scene with group 0."
                ),
            },
            "query_scene": {
                "label": "Query Scene",
                "params": {
                    "scene_id": {
                        "type": "string",
                        "required": True,
                        "label": "Scene",
                        "options_state": "scene_options",
                    },
                },
            },
            "query_all_scenes": {
                "label": "Query All Scenes",
                "params": {},
                "help": (
                    "Returns all scenes as raw JSON and refreshes the "
                    "scene picker list."
                ),
            },
        },
    }

    def __init__(self, *args: Any, **kwargs: Any) -> None:
        super().__init__(*args, **kwargs)
        self._client: httpx.AsyncClient | None = None
        self._app_key: str = ""
        # Last-known per-light schema (reconcile guard, dante/qsc pattern).
        self._light_schemas: dict[int, dict[str, Any]] = {}
        # Registered group ids (0 = the special all-lights group).
        self._group_ids: set[int] = set()
        # gid -> name, for scene picker labels.
        self._group_names: dict[int, str] = {}
        self._poll_cycle = 0

    # ── Connection lifecycle ──

    def _base_url(self) -> str:
        host = str(self.config.get("host", "")).strip()
        port = int(self.config.get("port", 80))
        return f"http://{host}" if port == 80 else f"http://{host}:{port}"

    async def connect(self) -> None:
        host = str(self.config.get("host", "")).strip()
        if not host:
            raise ConnectionError("Bridge IP address is required")
        self._app_key = str(self.config.get("app_key", "")).strip()

        self._client = httpx.AsyncClient(
            base_url=self._base_url(),
            timeout=float(self.config.get("timeout", 5.0)),
        )

        try:
            if not self._app_key:
                raise ConnectionFaultError(
                    "No app key configured — press the link button on the "
                    "bridge and run the \"Pair with Bridge\" setup action.",
                    code="auth_failed",
                )
            config = await self._request("GET", f"/api/{self._app_key}/config")
            self._apply_config(config)
        except httpx.TransportError as exc:
            await self._close_client()
            raise ConnectionError(
                f"Could not reach the Hue Bridge at {host}: {exc}"
            ) from exc
        except Exception:
            await self._close_client()
            raise

        self._connected = True
        self.set_state("connected", True)
        self.set_state("last_error", None)
        await self.events.emit(f"device.connected.{self.device_id}")
        log.info(f"[{self.device_id}] Connected to Hue Bridge at {host}")

        # Enumerate lights, groups, and scenes.
        try:
            await self._refresh_all()
        except httpx.TransportError as exc:
            raise ConnectionError(
                f"Hue Bridge at {host} stopped responding during enumeration: {exc}"
            ) from exc

        poll_interval = int(self.config.get("poll_interval", 10))
        if poll_interval > 0:
            await self.start_polling(poll_interval)

    async def disconnect(self) -> None:
        await self.stop_polling()
        await self._close_client()
        self._connected = False
        self.set_state("connected", False)
        await self.events.emit(f"device.disconnected.{self.device_id}")
        log.info(f"[{self.device_id}] Disconnected from Hue Bridge")

    async def _close_client(self) -> None:
        if self._client:
            await self._client.aclose()
            self._client = None

    async def poll(self) -> None:
        """Refresh light + group state every cycle; bridge config + scenes
        on a slower cadence. Transport errors propagate so the platform
        watchdog can flip the device offline."""
        if not self._client:
            return
        try:
            lights = await self._request("GET", f"/api/{self._app_key}/lights")
            groups = await self._request("GET", f"/api/{self._app_key}/groups")
            group0 = await self._fetch_group0()
            self._reconcile_lights(lights)
            self._reconcile_groups(groups, group0)

            self._poll_cycle += 1
            if self._poll_cycle % _METADATA_POLL_EVERY == 0:
                config = await self._request("GET", f"/api/{self._app_key}/config")
                self._apply_config(config)
                scenes = await self._request("GET", f"/api/{self._app_key}/scenes")
                self._update_scenes(scenes)
        except httpx.TransportError as exc:
            raise ConnectionError(
                f"Hue Bridge not responding: {exc}"
            ) from exc

    # ── Request plumbing ──

    async def _request(self, method: str, path: str, body: Any = None) -> Any:
        """Send one request and return the parsed JSON body.

        Transport errors (httpx.ConnectError / TimeoutException) propagate
        to the caller. A rejected app key — HTTP 401/403 or a Hue error
        type 1 — raises a typed auth_failed fault.
        """
        if not self._client:
            raise ConnectionError("Not connected")
        resp = await self._client.request(method, path, json=body)
        if resp.status_code in (401, 403):
            raise ConnectionFaultError(
                "The bridge rejected the app key — re-pair with the "
                "\"Pair with Bridge\" setup action.",
                code="auth_failed",
            )
        if resp.is_error:
            raise ConnectionError(
                f"Hue Bridge returned HTTP {resp.status_code} for {path}"
            )
        data = resp.json()
        self._raise_on_error(data)
        return data

    def _raise_on_error(self, data: Any) -> None:
        """Raise on Hue error entries ([{"error": {...}}, ...]).

        Type 1 (unauthorized) is a typed auth fault. A mixed
        success/error response (a group PUT where one field was rejected)
        is tolerated — the successes are applied and the error logged.
        """
        if not isinstance(data, list):
            return
        errors = [e["error"] for e in data
                  if isinstance(e, dict) and isinstance(e.get("error"), dict)]
        if not errors:
            return
        for err in errors:
            if err.get("type") == 1:
                raise ConnectionFaultError(
                    "The bridge rejected the app key — re-pair with the "
                    "\"Pair with Bridge\" setup action.",
                    code="auth_failed",
                )
        has_success = any(isinstance(e, dict) and "success" in e for e in data)
        first = errors[0]
        desc = str(first.get("description", "unknown error"))
        if has_success:
            log.warning(f"[{self.device_id}] Bridge accepted request partially: {desc}")
            self.set_state("last_error", desc)
            return
        if first.get("type") == 101:
            raise ValueError(
                "The bridge's link button has not been pressed. Press the "
                "round button on top of the bridge, then retry within 30 "
                "seconds."
            )
        raise ValueError(f"Bridge error: {desc}")

    # ── State mirroring ──

    def _apply_config(self, config: Any) -> None:
        if not isinstance(config, dict):
            return
        updates = {
            state_key: config[field]
            for field, state_key in _CONFIG_FIELDS.items()
            if field in config
        }
        if updates:
            self.set_states(updates)

    @staticmethod
    def _light_values(obj: dict[str, Any]) -> tuple[dict[str, Any], dict[str, Any]]:
        """Return (schema, values) for one light from its V1 document.

        The schema starts from the shared fields and adds one entry per
        capability field the light's state actually carries, so an on/off
        plug never grows a brightness prop. The platform ``online`` mirrors
        the Zigbee ``reachable`` flag (link-style child).
        """
        state = obj.get("state", {}) or {}
        schema = dict(_LIGHT_SHARED_SCHEMA)
        values: dict[str, Any] = {
            "name": str(obj.get("name", "")),
            "type": str(obj.get("type", "")),
            "model": str(obj.get("modelid", "")),
            "on": bool(state.get("on", False)),
            "online": bool(state.get("reachable", True)),
        }
        for prop in ("bri", "ct", "hue", "sat"):
            if prop in state:
                schema[prop] = _LIGHT_CAPABILITY_SCHEMA[prop]
                try:
                    values[prop] = int(state[prop])
                except (TypeError, ValueError):
                    values[prop] = 0
        if "xy" in state:
            schema["xy"] = _LIGHT_CAPABILITY_SCHEMA["xy"]
            xy = state.get("xy") or []
            values["xy"] = (
                f"{float(xy[0]):.4f},{float(xy[1]):.4f}" if len(xy) == 2 else ""
            )
        if "colormode" in state:
            schema["colormode"] = _LIGHT_CAPABILITY_SCHEMA["colormode"]
            values["colormode"] = str(state.get("colormode", ""))
        return schema, values

    def _reconcile_lights(self, lights: Any) -> None:
        if not isinstance(lights, dict):
            return
        seen: set[int] = set()
        for key in sorted(lights, key=lambda k: int(k) if str(k).isdigit() else 0):
            obj = lights[key]
            if not str(key).isdigit() or not isinstance(obj, dict):
                continue
            lid = int(key)
            seen.add(lid)
            schema, values = self._light_values(obj)
            prev = self._light_schemas.get(lid)
            if prev == schema and self.is_child_registered("light", lid):
                self.set_child_state_batch("light", lid, values)
            else:
                if self.is_child_registered("light", lid):
                    self.deregister_child("light", lid)
                self.register_child("light", lid, schema=schema, initial_state=values)
            self._light_schemas[lid] = schema
        for lid in list(self._light_schemas):
            if lid not in seen:
                self.deregister_child("light", lid)
                self._light_schemas.pop(lid, None)
        self.set_state("light_count", len(seen))

    @staticmethod
    def _group_values(obj: dict[str, Any]) -> dict[str, Any]:
        state = obj.get("state", {}) or {}
        action = obj.get("action", {}) or {}
        values: dict[str, Any] = {
            "name": str(obj.get("name", "")),
            "type": str(obj.get("type", "")),
            "room_class": str(obj.get("class", "")),
            "any_on": bool(state.get("any_on", False)),
            "all_on": bool(state.get("all_on", False)),
            "lights": ",".join(str(x) for x in obj.get("lights", []) or []),
        }
        if "bri" in action:
            try:
                values["bri"] = int(action["bri"])
            except (TypeError, ValueError):
                pass
        return values

    def _reconcile_groups(self, groups: Any, group0: dict[str, Any] | None) -> None:
        entries: dict[int, dict[str, Any]] = {}
        if isinstance(group0, dict):
            entries[0] = group0
        if isinstance(groups, dict):
            for key, obj in groups.items():
                if str(key).isdigit() and isinstance(obj, dict):
                    entries[int(key)] = obj
        for gid in sorted(entries):
            values = self._group_values(entries[gid])
            self._group_names[gid] = values["name"]
            if self.is_child_registered("group", gid):
                self.set_child_state_batch("group", gid, values)
            else:
                self.register_child("group", gid, initial_state=values)
            self._group_ids.add(gid)
        # Group 0 always exists on the bridge — never deregister it just
        # because one /groups/0 fetch failed.
        for gid in list(self._group_ids):
            if gid not in entries and gid != 0:
                self.deregister_child("group", gid)
                self._group_ids.discard(gid)
                self._group_names.pop(gid, None)
        self.set_state("group_count", len([g for g in self._group_ids if g != 0]))

    async def _fetch_group0(self) -> dict[str, Any] | None:
        """GET /groups/0 — the all-lights group is excluded from /groups."""
        try:
            data = await self._request("GET", f"/api/{self._app_key}/groups/0")
        except httpx.TransportError:
            raise
        except ConnectionError:
            raise
        except Exception as exc:
            log.warning(f"[{self.device_id}] groups/0 fetch failed: {exc}")
            return None
        if isinstance(data, dict):
            data.setdefault("name", "All Lights")
            return data
        return None

    def _update_scenes(self, scenes: Any) -> None:
        if not isinstance(scenes, dict):
            return
        options: list[dict[str, str]] = []
        for sid, obj in scenes.items():
            if not isinstance(obj, dict):
                continue
            label = str(obj.get("name", sid))
            gid = obj.get("group")
            if gid is not None and str(gid).isdigit():
                group_name = self._group_names.get(int(gid))
                if group_name:
                    label = f"{label} ({group_name})"
            options.append({"value": str(sid), "label": label})
        options.sort(key=lambda o: o["label"].lower())
        self.set_states({
            "scene_options": json.dumps(options),
            "scene_count": len(options),
        })

    async def _refresh_all(self) -> dict[str, int]:
        """Full re-read: one full-state GET plus the group-0 fetch."""
        full = await self._request("GET", f"/api/{self._app_key}")
        if isinstance(full, dict):
            self._apply_config(full.get("config", {}))
            self._reconcile_lights(full.get("lights", {}))
            group0 = await self._fetch_group0()
            self._reconcile_groups(full.get("groups", {}), group0)
            self._update_scenes(full.get("scenes", {}))
        return {
            "lights": len(self._light_schemas),
            "groups": len(self._group_ids),
            "scenes": int(self.get_state("scene_count") or 0),
        }

    async def refresh_children(self) -> dict[str, int]:
        """Backs the IDE "Refresh from Device" button."""
        if not self._client:
            raise ConnectionError(f"[{self.device_id}] Not connected")
        return await self._refresh_all()

    # ── Command surface ──

    async def send_command(self, command: str, params: dict[str, Any] | None = None) -> Any:
        params = params or {}
        if not self._client:
            raise ConnectionError(f"[{self.device_id}] Not connected")
        key = self._app_key

        match command:
            case "create_user":
                return await self._request(
                    "POST", "/api", {"devicetype": _DEVICETYPE}
                )
            case "query_config":
                config = await self._request("GET", f"/api/{key}/config")
                self._apply_config(config)
                return config
            case "query_full_state":
                full = await self._request("GET", f"/api/{key}")
                if isinstance(full, dict):
                    self._apply_config(full.get("config", {}))
                    self._reconcile_lights(full.get("lights", {}))
                    group0 = await self._fetch_group0()
                    self._reconcile_groups(full.get("groups", {}), group0)
                    self._update_scenes(full.get("scenes", {}))
                return full
            case "refresh":
                return await self._refresh_all()

            case "light_on":
                return await self._light_put(params, {"on": True})
            case "light_off":
                return await self._light_put(params, {"on": False})
            case "light_set_brightness":
                return await self._light_put(
                    params, {"on": True, "bri": int(params["bri"])}
                )
            case "light_set_color_temp":
                return await self._light_put(
                    params, {"on": True, "ct": int(params["ct"])}
                )
            case "light_set_hue_sat":
                return await self._light_put(
                    params,
                    {"on": True, "hue": int(params["hue"]), "sat": int(params["sat"])},
                )
            case "light_set_xy":
                return await self._light_put(
                    params,
                    {"on": True, "xy": [float(params["x"]), float(params["y"])]},
                )
            case "light_alert":
                return await self._light_put(
                    params, {"alert": str(params.get("alert", "select"))}
                )
            case "query_light":
                lid = int(params["light_id"])
                obj = await self._request("GET", f"/api/{key}/lights/{lid}")
                if isinstance(obj, dict):
                    self._reconcile_one_light(lid, obj)
                return obj
            case "query_all_lights":
                lights = await self._request("GET", f"/api/{key}/lights")
                self._reconcile_lights(lights)
                return lights

            case "group_on":
                return await self._group_put(params, {"on": True})
            case "group_off":
                return await self._group_put(params, {"on": False})
            case "group_set_brightness":
                return await self._group_put(
                    params, {"on": True, "bri": int(params["bri"])}
                )
            case "group_set_color_temp":
                return await self._group_put(
                    params, {"on": True, "ct": int(params["ct"])}
                )
            case "group_set_hue_sat":
                return await self._group_put(
                    params,
                    {"on": True, "hue": int(params["hue"]), "sat": int(params["sat"])},
                )
            case "group_recall_scene":
                return await self._group_put(
                    params, {"scene": str(params["scene_id"]).strip()}
                )
            case "query_group":
                gid = int(params["group_id"])
                obj = await self._request("GET", f"/api/{key}/groups/{gid}")
                if isinstance(obj, dict):
                    if gid == 0:
                        obj.setdefault("name", "All Lights")
                    values = self._group_values(obj)
                    self._group_names[gid] = values["name"]
                    if self.is_child_registered("group", gid):
                        self.set_child_state_batch("group", gid, values)
                    else:
                        self.register_child("group", gid, initial_state=values)
                        self._group_ids.add(gid)
                return obj
            case "query_all_groups":
                groups = await self._request("GET", f"/api/{key}/groups")
                group0 = await self._fetch_group0()
                self._reconcile_groups(groups, group0)
                return groups

            case "all_on":
                return await self._group_put({"group_id": 0}, {"on": True})
            case "all_off":
                return await self._group_put({"group_id": 0}, {"on": False})
            case "recall_scene":
                return await self._group_put(
                    {"group_id": 0}, {"scene": str(params["scene_id"]).strip()}
                )
            case "query_scene":
                sid = str(params["scene_id"]).strip()
                return await self._request("GET", f"/api/{key}/scenes/{sid}")
            case "query_all_scenes":
                scenes = await self._request("GET", f"/api/{key}/scenes")
                self._update_scenes(scenes)
                return scenes

            case _:
                log.warning(f"[{self.device_id}] Unknown command: {command}")
                return None

    async def _light_put(self, params: dict[str, Any], body: dict[str, Any]) -> Any:
        """PUT a light state change and apply the bridge's per-field
        success confirmations to the child immediately."""
        lid = int(params["light_id"])
        result = await self._request(
            "PUT", f"/api/{self._app_key}/lights/{lid}/state", body
        )
        self._apply_put_success(result, _LIGHT_SUCCESS_RE, self._apply_light_field)
        return result

    async def _group_put(self, params: dict[str, Any], body: dict[str, Any]) -> Any:
        """PUT a group action, apply the confirmations to the group child,
        then re-read lights + groups — a group action fans out to member
        lights the confirmation doesn't enumerate."""
        gid = int(params["group_id"])
        result = await self._request(
            "PUT", f"/api/{self._app_key}/groups/{gid}/action", body
        )
        self._apply_put_success(result, _GROUP_SUCCESS_RE, self._apply_group_field)
        try:
            lights = await self._request("GET", f"/api/{self._app_key}/lights")
            groups = await self._request("GET", f"/api/{self._app_key}/groups")
            group0 = await self._fetch_group0()
            self._reconcile_lights(lights)
            self._reconcile_groups(groups, group0)
        except httpx.TransportError as exc:
            log.warning(
                f"[{self.device_id}] Post-command refresh failed: {exc} "
                f"(state converges on the next poll)"
            )
        return result

    @staticmethod
    def _apply_put_success(result: Any, pattern: re.Pattern, apply_fn) -> None:
        if not isinstance(result, list):
            return
        for entry in result:
            if not isinstance(entry, dict):
                continue
            success = entry.get("success")
            if not isinstance(success, dict):
                continue
            for address, value in success.items():
                m = pattern.match(str(address))
                if m:
                    apply_fn(int(m.group(1)), m.group(2), value)

    def _apply_light_field(self, lid: int, field: str, value: Any) -> None:
        if not self.is_child_registered("light", lid):
            return
        schema = self._light_schemas.get(lid, {})
        updates: dict[str, Any] = {}
        if field == "on":
            updates["on"] = bool(value)
        elif field in ("bri", "ct", "hue", "sat") and field in schema:
            try:
                updates[field] = int(value)
            except (TypeError, ValueError):
                pass
        elif field == "xy" and "xy" in schema:
            if isinstance(value, (list, tuple)) and len(value) == 2:
                updates["xy"] = f"{float(value[0]):.4f},{float(value[1]):.4f}"
        if updates:
            try:
                self.set_child_state_batch("light", lid, updates)
            except ValueError:
                pass

    def _apply_group_field(self, gid: int, field: str, value: Any) -> None:
        if not self.is_child_registered("group", gid):
            return
        updates: dict[str, Any] = {}
        if field == "on":
            # A confirmed group on/off is deterministic for both flags.
            updates["any_on"] = bool(value)
            updates["all_on"] = bool(value)
        elif field == "bri":
            try:
                updates["bri"] = int(value)
            except (TypeError, ValueError):
                pass
        if updates:
            try:
                self.set_child_state_batch("group", gid, updates)
            except ValueError:
                pass

    def _reconcile_one_light(self, lid: int, obj: dict[str, Any]) -> None:
        schema, values = self._light_values(obj)
        prev = self._light_schemas.get(lid)
        if prev == schema and self.is_child_registered("light", lid):
            self.set_child_state_batch("light", lid, values)
        else:
            if self.is_child_registered("light", lid):
                self.deregister_child("light", lid)
            self.register_child("light", lid, schema=schema, initial_state=values)
        self._light_schemas[lid] = schema

    # ── Device settings ──

    async def set_device_setting(self, key: str, value: Any) -> Any:
        if key != "bridge_name":
            raise NotImplementedError(f"Unknown device setting: {key}")
        if not self._client:
            raise ConnectionError(f"[{self.device_id}] Not connected")
        name = str(value).strip()
        if not name:
            raise ValueError("Bridge name cannot be empty")
        await self._request(
            "PUT", f"/api/{self._app_key}/config", {"name": name}
        )
        config = await self._request("GET", f"/api/{self._app_key}/config")
        self._apply_config(config)
        return self.get_state("bridge_name")

    # ── Setup wizard: pair with the bridge's link button ──

    async def run_setup_action(
        self, action_id: str, params: dict[str, Any], progress: Any
    ) -> dict[str, Any]:
        """Pair with the bridge (out-of-band; runs while the device is
        offline). Verifies a Hue bridge answers at the configured host,
        requests an app key (the user must have pressed the link button),
        and optionally saves the key + reconnects."""
        if action_id != "pair_bridge":
            raise ValueError(f"Unknown setup action: {action_id}")

        host = str(self.config.get("host", "")).strip()
        if not host:
            raise ValueError("No bridge IP address configured")
        save = bool(params.get("save", True))

        async with httpx.AsyncClient(
            base_url=self._base_url(),
            timeout=float(self.config.get("timeout", 5.0)),
        ) as client:
            await progress(f"Checking the bridge at {host}…", 10)
            try:
                resp = await client.get("/api/config")
            except httpx.TransportError as exc:
                raise ConnectionError(
                    f"Could not reach a Hue Bridge at {host}: {exc}"
                ) from exc
            info = resp.json() if resp.status_code == 200 else {}
            if not isinstance(info, dict) or "bridgeid" not in info:
                raise ConnectionError(
                    f"The device at {host} answered, but does not look like "
                    f"a Hue Bridge (no bridgeid in /api/config)."
                )

            await progress(
                "Requesting an app key — the link button must have been "
                "pressed within the last 30 seconds…",
                40,
            )
            resp = await client.post("/api", json={"devicetype": _DEVICETYPE})
            data = resp.json() if resp.status_code == 200 else []
            username = ""
            for entry in data if isinstance(data, list) else []:
                if not isinstance(entry, dict):
                    continue
                err = entry.get("error")
                if isinstance(err, dict):
                    if err.get("type") == 101:
                        raise ConnectionError(
                            "The bridge's link button has not been pressed. "
                            "Press the round button on top of the bridge, "
                            "then run this action again within 30 seconds."
                        )
                    raise ConnectionError(
                        f"Pairing failed: {err.get('description', 'unknown error')}"
                    )
                success = entry.get("success")
                if isinstance(success, dict) and success.get("username"):
                    username = str(success["username"])
            if not username:
                raise ConnectionError(
                    "The bridge did not return an app key. Retry after "
                    "pressing the link button."
                )

        saved = False
        if save:
            # The app key is the bridge's standing credential — persist it
            # so every future connect uses it.
            await self.request_config_update({"app_key": username})
            saved = True
            await progress("Reconnecting with the new app key…", 90)
            await self.request_reconnect()
        await progress("Done", 100)

        return {
            "paired": True,
            "bridge_name": str(info.get("name", "")),
            "bridge_id": str(info.get("bridgeid", "")),
            "app_key": username,
            "saved": saved,
        }
